# Site Settings
title:               Jayeol Chun
tagline:             Profile & Blog
description:
baseurl:            #"/Lagrange"
url:                #"https://chunjy92.github.io"
github:
  url:               #"https://github.com/chunjy92/chunjy92.github.io"
author:
  name:              "Jayeol Chun"
  email:             "chunjy92@gmail.com"
  twitter:           "chunjy92"
  instagram:         #"paululele"
  github:            "chunjy92"
  facebook:          "chunjy92"
  linkedin:          "chunjy92"
  rss:               "aprilharu"
navigation:
- title: About
  url: /about
- title: Projects
  url: /projects
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
