title:               Jayeol Chun
description:         optimizing life

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-sitemap, jekyll-seo-tag]
