title:               Jayeol Chun
description:         Liberal Arts at Emory | CS Ph.D. at Brandeis

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-sitemap, jekyll-seo-tag]
